apiVersion: v1
kind: Secret
metadata:
  name: guacamole-secrets
  labels:
    app.kubernetes.io/name: guacamole
    app.kubernetes.io/component: guacamole
type: Opaque
stringData:
  POSTGRES_DB: guacamole_db
  POSTGRES_USER: guacamole_user
  POSTGRES_PASSWORD: CHANGE_ME
  LDAP_HOSTNAME: ldap.tjse.jus.br
  LDAP_SEARCH_BIND_DN: CN=svc-segportal,OU=Servicos,DC=tjse,DC=jus,DC=br
  LDAP_SEARCH_BIND_PASSWORD: CHANGE_ME
  MFA_RADIUS_HOST: radius.tjse.jus.br
  MFA_RADIUS_SECRET: CHANGE_ME
