apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: registry.tjse.jus.br/segportal/guacamole
    newTag: latest
  - name: registry.tjse.jus.br/segportal/guacd
    newTag: latest
  - name: registry.tjse.jus.br/segportal/egress-proxy
    newTag: latest

configMapGenerator:
  - name: segportal-common
    behavior: merge
    literals:
      - GUACAMOLE_HOSTNAME=segportal.tjse.jus.br
      - SESSION_TIMEOUT_MINUTES=60
      - MFA_ENABLED=true

patches:
  - target:
      kind: Deployment
      name: guacamole
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: guacd
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
