apiVersion: v1
kind: ConfigMap
metadata:
  name: segportal-common
  labels:
    app.kubernetes.io/name: segportal
    app.kubernetes.io/component: config
data:
  GUACD_HOSTNAME: guacd
  GUACD_PORT: "4822"
  # LDAP desligado por padrão — admin configura apontamentos e liga depois
  LDAP_ENABLED: "false"
  LDAP_PORT: "636"
  LDAP_ENCRYPTION_METHOD: ssl
  LDAP_USERNAME_ATTRIBUTE: sAMAccountName
  LDAP_USER_BASE_DN: OU=Usuarios,DC=aqne,DC=jus,DC=br
  LDAP_GROUP_BASE_DN: OU=Grupos,DC=aqne,DC=jus,DC=br
  LDAP_MEMBER_ATTRIBUTE: member
  LDAP_USER_SEARCH_FILTER: "(objectClass=user)"
  LDAP_GROUP_SEARCH_FILTER: "(objectClass=group)"
  LDAP_CA_CHAIN_FILE: /etc/guacamole/certs/ldap-ca-chain.pem
  LDAP_TRUSTSTORE_FILE: /etc/guacamole/certs/ldap-truststore.jks
  EGRESS_PROXY_HOST: proxy-egress
  EGRESS_PROXY_PORT: "3128"
  SESSION_TIMEOUT_MINUTES: "60"
  MFA_ENABLED: "false"
  MFA_RADIUS_PORT: "1812"
  GUACAMOLE_HOSTNAME: segportal.aqne.jus.br
