apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: segportal

resources:
  - namespace.yaml
  - configmap-common.yaml
  - ../postgres
  - ../guacd
  - ../guacamole
  - ../proxy-egress
  - ../web-browser
  - ../ingress

commonLabels:
  app.kubernetes.io/part-of: segportal
  app.kubernetes.io/managed-by: kustomize
