apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: registry.tjse.jus.br/segportal/guacamole
    newTag: staging
  - name: registry.tjse.jus.br/segportal/guacd
    newTag: staging
  - name: registry.tjse.jus.br/segportal/egress-proxy
    newTag: staging

configMapGenerator:
  - name: segportal-common
    behavior: merge
    literals:
      - GUACAMOLE_HOSTNAME=segportal-stg.tjse.jus.br

patches:
  - target:
      kind: Ingress
      name: segportal
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: segportal-stg.tjse.jus.br
      - op: replace
        path: /spec/tls/0/hosts/0
        value: segportal-stg.tjse.jus.br
